trigger:
  - main

pool:
  name: Self-hosted

steps:
  # Step 1: Terraform Init
  - task: TerraformTaskV5@5
    displayName: "Terraform Init"
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module/dev'
      backendServiceArm: 'Self-hosted'
      backendAzureRmOverrideSubscriptionID: 'c03f6878-4621-428c-b360-d9282cbb1a98'
      backendAzureRmResourceGroupName: 'rg_strg'
      backendAzureRmStorageAccountName: 'strgfortfstate'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  # Step 2: Terraform Validate
  - task: TerraformTaskV5@5
    displayName: "Terraform Validate"
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module/dev'

  # Step 3: Terraform Plan
  - task: TerraformTaskV5@5
    displayName: "Terraform Plan"
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module/dev'
      environmentServiceNameAzureRM: 'Self-hosted'

  # Step 4: Terraform Apply
  - task: TerraformTaskV5@5
    displayName: "Terraform Apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module/dev'
      environmentServiceNameAzureRM: 'Self-hosted'
      
